// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1) {
  return window['go']['main']['App']['ChatWithAI'](arg1);
}

export function CheckUser() {
  return window['go']['main']['App']['CheckUser']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}
