// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChatWithAI(arg1:string):Promise<main.ChatResult>;

export function CheckUser():Promise<main.CheckResult>;

export function GetMessages():Promise<main.GetMessagesResult>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Register(arg1:string,arg2:string):Promise<main.RegisterResult>;
