// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChatWithAI(arg1:string,arg2:string):Promise<main.ChatResult>;

export function GetCurrentUser():Promise<main.CheckResult>;

export function Greet(arg1:string):Promise<string>;

export function LoadChatHistory():Promise<main.GetMessagesResult>;

export function SignOut():Promise<main.SignOutResult>;

export function Signin(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Signup(arg1:string,arg2:string):Promise<main.RegisterResult>;
