// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1) {
  return window["go"]["main"]["App"]["ChatWithAI"](arg1);
}

export function Greet(arg1) {
  return window["go"]["main"]["App"]["Greet"](arg1);
}
