// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1, arg2) {
  return window['go']['main']['App']['ChatWithAI'](arg1, arg2);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadChatHistory() {
  return window['go']['main']['App']['LoadChatHistory']();
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function Signin(arg1, arg2) {
  return window['go']['main']['App']['Signin'](arg1, arg2);
}

export function Signup(arg1, arg2) {
  return window['go']['main']['App']['Signup'](arg1, arg2);
}
